flag rename of Fold Angle
w3c/das-charter pull request #112
Opened 2021-05-18 14:50 UTC by samuelweiler

and clarify this history

2021-05-18 17:12 UTC, anssiko requested changes
Fixed a few typos.

2021-05-18 17:12 UTC, anssiko commented on DASCharter-2021.html
> +                Added Contact Picker API, Idle Detection API, and Compute Pressure to the group's tentative deliverables.  Changed the Fold Angle Sensor API from a tenatitive to a normative deliverab
```suggestion
                Added Contact Picker API, Idle Detection API, and Compute Pressure to the group's tentative deliverables.  Changed the Fold Angle Sensor API from a tentative to a normative deliverable, renaming it as the Device Posture API.
```

2021-06-01 13:52 UTC, xfq approved these changes

2021-06-01 16:22 UTC, anssiko approved these changes

2021-06-02 11:50 UTC, merged

2021-06-02 11:50 UTC, xfq commented
Thank you!